#spring.datasource.url=jdbc:mysql://localhost:3306/dbname
#spring.datasource.username=root
#spring.datasource.password=password
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy
#spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

spring:
    datasource:
        initialize: true
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
        driverClassName: org.h2.Driver
        username: sa
        password:
    h2:
        console:
            enabled: true

leaf:
    security:
        secret: secret
